### PR TITLE
Incorporate dependencies under 'vendor/' using 'godep'

### PR DESCRIPTION
**Pull request by mredivo**
This uses 'godep' (https://github.com/tools/godep) to copy dependencies to the 'vendor/' directory.

A new target has been added to the Makefile to perform this step without missing any dependencies:

```
PACKAGES = . ./api ./config ./datastore ./listener ./middleware ./pearson
...
+vendorize:
+       godep save $(PACKAGES)
+
```

This is the only use of godep required; the Go compiler can do the rest.

To ensure that the files under 'vendor/' are the ones used during a build, it is necessary to use one of:

* go 1.5 with export GO15VENDOREXPERIMENT=1
* go 1.6

### CODE REVIEW

**Comment by jeffpierce** [comment]
I think you need to merge in master so that the otium/queue package gets picked up.  That's the latest CI failure.

**Comment by jeffpierce** [comment]
Otherwise, LGTM!

**Comment by mredivo** [comment]
The circle.yml file appears to be correct now, but 'make test' is still failing.

Building with SSH enabled, logging in, and simply running 'make test' passes:

```
ubuntu@box603:~/.go_workspace/src/github.com/jeffpierce/cassabon$ env | grep GO
GO15VENDOREXPERIMENT=1
GOPATH=/home/ubuntu/.go_workspace:/usr/local/go_workspace

ubuntu@box603:~/.go_workspace/src/github.com/jeffpierce/cassabon$ make test
go test -race . ./api ./config ./datastore ./listener ./middleware ./pearson
?   	github.com/jeffpierce/cassabon	[no test files]
?   	github.com/jeffpierce/cassabon/api	[no test files]
ok  	github.com/jeffpierce/cassabon/config	1.049s
?   	github.com/jeffpierce/cassabon/datastore	[no test files]
ok  	github.com/jeffpierce/cassabon/listener	1.375s
?   	github.com/jeffpierce/cassabon/middleware	[no test files]
ok  	github.com/jeffpierce/cassabon/pearson	1.009s
go test ./logging
ok  	github.com/jeffpierce/cassabon/logging	0.004s
```

Not sure how to account for that.

**Comment by jeffpierce** [comment]
Taking a look.

**Comment by mredivo** [comment]
To confirm. otium/queue is indeed present in this branch:

`https://github.com/jeffpierce/cassabon/tree/mredivo/vendorize/vendor/github.com/otium/queue`

**Comment by mredivo** [comment]
Given that a hack was required to make the tests pass, it's unclear why the build succeeded. Maybe there's a bug in Go, in that 'build' and 'test' follow different rules?

**Comment by jeffpierce** [comment]
Possibly?

I'm on Go 1.6 on my workstation.  I wonder if making sure the tests run with that would solve the problem.

Either way, the hack doesn't really change anything about the test itself, and it passed.  Merge it in when you're ready.

**Comment by jeffpierce** [comment]
Tagging #111 and #104.

**Pull request merged**
